### ISSUE TITLE
Axis to Float Causing Error

### ISSUE THREAD

**Issue by Wonderflex** [kenjiqq/qq-nodes-comfyui#3]
Hello,

When trying to run an "Axis to Float" node I'm given this error:

![image](https://github.com/kenjiqq/qq-nodes-comfyui/assets/112730878/5668abc7-8cfd-46ec-9379-5a423c83c241)

Currently the workaround of running an Axis to Number then Number to Float works:

![image](https://github.com/kenjiqq/qq-nodes-comfyui/assets/112730878/3aecbcfb-0f8e-4979-a139-e3696182c9c6)

This is the formatting of my input text:

![image](https://github.com/kenjiqq/qq-nodes-comfyui/assets/112730878/a352f891-ac2a-4351-b12d-03dec358dcbd)

When attempting to use the new Text Splitter with Axis to Float a different error is generated:

![image](https://github.com/kenjiqq/qq-nodes-comfyui/assets/112730878/fcf15f75-c106-4323-89b3-8eea174adb15)

This error does not occur when using the Axis to Number then Number to Float workaround.

**Comment by kenjiqq** [comment]
The "Axis to" nodes are not actually doing any converting they are just there to fix the output symbol in the UI node so that you can connect it to the next node you need that only takes a float/number etc, since you can't draw a connection between a STRING output and a FLOAT input for instance. 
You should use the "Axis To" node that matches whatever you put in on the input side. So in this case you are putting STRING into the array that is going into the Grid node so you should use Axis to STRING on the output side as well, then you can convert the string to whatever you want. Or you can convert the STRING to a number/float on the input side before you put it in the array, up to you. 

I'm guessing it's only luck that the Axis to number works for you where because the code in number to float node actually also happens to be able to handle a string coming in.

**Comment by Wonderflex** [comment]
> The "Axis to" nodes are not actually doing any converting they are just there to fix the output symbol in the UI node so that you can connect it to the next node you need that only takes a float/number etc, since you can't draw a connection between a STRING output and a FLOAT input for instance. You should use the "Axis To" node that matches whatever you put in on the input side. So in this case you are putting STRING into the array that is going into the Grid node so you should use Axis to STRING on the output side as well, then you can convert the string to whatever you want. Or you can convert the STRING to a number/float on the input side before you put it in the array, up to you.
> 
> I'm guessing it's only luck that the Axis to number works for you where because the code in number to float node actually also happens to be able to handle a string coming in.

Thank you for the explanation.  Please feel free to close.
